import {
  MagnifyingGlassIcon,
  HandRaisedIcon,
  BoltIcon,
  MapPinIcon,
  UserIcon,
  ArrowPathIcon,
  SparklesIcon,
  UsersIcon,
  ClipboardDocumentIcon,
  ArrowTrendingUpIcon,
  SwatchIcon,
  ClockIcon,
  CheckCircleIcon,
  PhoneIcon,
  EnvelopeIcon,
  EyeIcon,
  PlusIcon,
  MinusIcon,
} from '@heroicons/react/24/outline'

export const iconMap = {
  search:    MagnifyingGlassIcon,
  hand:      HandRaisedIcon,
  bolt:      BoltIcon,
  'map-pin': MapPinIcon,
  person:    UserIcon,
  run:       ArrowPathIcon,
  leaf:      SparklesIcon,
  users:     UsersIcon,
  clipboard: ClipboardDocumentIcon,
  trending:  ArrowTrendingUpIcon,
  shirt:     SwatchIcon,
  clock:     ClockIcon,
  check:     CheckCircleIcon,
  phone:     PhoneIcon,
  envelope:  EnvelopeIcon,
  eye:       EyeIcon,
  plus:      PlusIcon,
  minus:     MinusIcon,
}
